### ISSUE TITLE
Retiring this gem

### ISSUE THREAD

**Issue by tijmenb** [alphagov/govuk-lint#109]
GOV.UK is considering retiring this gem in favour of a Ruby-specific gem for Rubocop and using NPM packages to lint CSS and Javascript. The internal GOV.UK RFC is here: https://github.com/alphagov/govuk-rfcs/pull/100.

Opening this issue for visibility, since this gem is used across GDS and government.

**Comment by henrytk** [comment]
Was a decision made to retire the gem? If so, where can I find the alternative?

**Comment by cbaines** [comment]
> Was a decision made to retire the gem? If so, where can I find the alternative?

As above, as this gem is a wrapper around Rubocop and scss_lint, the general trajectory is to use those tools directly (or alternatives to those tools directly). A gem may still be used for providing common configuration.

**Comment by henrytk** [comment]
> A gem may still be used for providing common configuration.

It's that gem (common configuration) we are after. Is that something you will publish?

**Comment by cbaines** [comment]
> It's that gem (common configuration) we are after. Is that something you will publish?

In some cases, rather than using the `govuk-lint-ruby` script within this gem, we're just using the configuration already.

This is one example of how you can do this: https://github.com/alphagov/content-data-api/blob/master/.rubocop.yml#L1-L2

**Comment by lfdebrux** [comment]
Should the GDS Way be updated to reflect this new advice? Currently it seems to suggest just using this gem https://gds-way.cloudapps.digital/manuals/programming-languages/ruby.html

**Comment by cbaines** [comment]
> Should the GDS Way be updated to reflect this new advice? Currently it seems to suggest just using this gem https://gds-way.cloudapps.digital/manuals/programming-languages/ruby.html

Probably.

**Comment by theseanything** [comment]
This has been deprecated

**Comment by tijmenb** [comment]
💯
