### ISSUE TITLE
Overriding Rubocop rules

### ISSUE THREAD

**Issue by chrisroos** [alphagov/govuk-lint#14]
Unless I'm missing something, it doesn't look as though it's possible to override the Rubocop rules included in this repo.

It looks as though Rubocop will only respect the last `--config` option if it's specified multiple times; which means that I can't use `govuk-ruby-lint --config </path/to/app-specific-rules>`.

This seems to go against the [Recommended usage paragraph in the styleguides repo](https://github.com/alphagov/styleguides/blob/master/using-rubocop.md#recommended-usage), which states:

> Choice of cops to use is left to the discretion of your team.

I can also imagine that this lack of customisation may make it hard to run govuk-lint-ruby as part of the build process in an existing project; you'd have to fix all violations before you could start using this utility. If it was possible to customise the rules then I could imagine disabling all Cops that are not yet satisfied, adding govuk-lint-ruby to the build process and then slowly fixing violations and enabling the disabled Cops over time.

Am I missing something, or is overriding the rules not supported?

**Comment by boffbowsh** [comment]
There's no way currently of overriding the rules to be used. This is a limitation of Rubocop itself. One possible workaround would be to generate a temporary YAML file for each run that inherits first the included config and then the repo-supplied one, and uses the generated YAML file instead. This hasn't been a required use case so far, so the feature wasn't added.

> you'd have to fix all violations before you could start using this utility. 

The intention for larger legacy projects is to use the `--diff` functionality in CI and fix offences as you change code around them.
