### ISSUE TITLE
Discuss: only configure exceptions to Rubocop in this repo

### ISSUE THREAD

**Issue by tijmenb** [alphagov/govuk-lint#47]
Currently, this repo configures a large number of cops in [the combined YAML files](https://github.com/alphagov/govuk-lint/tree/master/configs/rubocop).

The original `.yaml` came from the [styleguides repo](https://github.com/alphagov/styleguides). Since they were produced, Rubocop has gained a lot of new cops. 

This means the list in this repo is no longer complete. The explicitness we gained by having the default .yaml's duplicated here is greatly diminished (I'm guessing the explicitness was the reason to have them here) .

Instead of adding or re-generating the list, I propose that we remove all configuration from this repo that duplicates the Rubocop defaults. 

For example, `BlockAlignment` is enabled in [our config](https://github.com/alphagov/govuk-lint/blob/e159e4982d6be8d1ad94708010cc5224ae0445d5/configs/rubocop/gds-ruby-styleguide.yml#L5-L8) and also in the [Rubocop defaults](https://github.com/bbatsov/rubocop/blob/03c1f008e5153e7c3396be56fe5b660035d2f773/config/enabled.yml#L943-L945), which means that we can remove it from this repo.

**Comment by h-lame** [comment]
The upside of having a complete set of explicit config in our repo is that as and when the maintainers of rubocop decide to change the default settings of some cops, we won't suddenly find we have to change code that previously was acceptable to the linter.  

The downside is that the maintainers often rename cops and so upgrades mean we don't have config for those cops and so are left in a false sense of security about the whims of the linter.

Realistically I think either approach is fine.  What we might need is a documented process of what you need to do when you bump the rubocop version to make sure our config is still complete for all cops or doesn't duplicate defaults and where defaults have changed we've re-inlined the config to use the old settings.
