### ISSUE TITLE
integration with linter (Atom)

### ISSUE THREAD

**Issue by dynamicworkplace** [alphagov/govuk-lint#61]
Hi

I'm using Atom with linter-rubocop and I'm looking for the best way to integrate the rules so I get 'live' feedback on code as it is written. Does anyone use govuk-lint rules with a linter - I'd be grateful for any advice.

Thank you
Dan

**Comment by theseanything** [comment]
You can now use rubocop-govuk to import the same rules and use rubocop natively.
