### ISSUE TITLE
scss_lint is being deprecated

### ISSUE THREAD

**Issue by robinwhittleton** [alphagov/govuk-lint#70]
https://github.com/brigade/scss-lint#notice-consider-other-tools-before-adopting-scss-lint

>The Sass core team is now building Sass in [Dart instead of Ruby](http://blog.sass-lang.com/posts/1022316-announcing-dart-sass), and will no longer be maintaining the Ruby implementation unless a maintainer steps up to help. Since the SCSS-Lint project relies on the Ruby Sass implementation, this means it will eventually not support the latest Sass features and bug fixes.

>Two alternatives worthy of consideration are [stylelint](http://stylelint.io/) and [sass-lint](https://github.com/sasstools/sass-lint), with sass-lint having closer feature parity to SCSS-lint.

**Comment by theseanything** [comment]
This gem has been deprecated. This issue should be re-raised in https://github.com/alphagov/scss-lint-govuk.
