### ISSUE TITLE
randomly lint errors when run in diff mode

### ISSUE THREAD

**Issue by mcgoooo** [alphagov/govuk-lint#74]
This is a stub issue to next time we see it

i have been seeing on Jenkins, different results from the diff than on my local machine, and it is bringing up files unrelated to the change. The ideal solution would be to just not run it on diff mode, but i understand that may take a while.

**Comment by fofr** [comment]
This is a good example: https://github.com/alphagov/government-frontend/pull/331#pullrequestreview-34910806

**Comment by fofr** [comment]
Not seen this for a while. Closing until it resurfaces.
