### ISSUE TITLE
Lint git commit messages

### ISSUE THREAD

**Issue by fofr** [alphagov/govuk-lint#76]
A suggestion: We could _lint_ git commit messages based on the rules set out in our style guide here: 
https://github.com/alphagov/styleguides/blob/master/git.md

A tool based around [Tim Pope's blog post](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html) would work:
https://github.com/m1foley/fit-commit

This would avoid things like:
https://github.com/alphagov/govuk-frontend/pull/17#issuecomment-303358855

**Comment by theseanything** [comment]
This gem is now deprecated and we've move away from "all-in-one" linting tools.
