### ISSUE TITLE
Consider increasing the Max option for RSpec/NestedGroups by default

### ISSUE THREAD

**Issue by floehopper** [alphagov/govuk-lint#91]
[The default for this option is 2][1] which seems somewhat extreme. I think I'd be happy to increase this to 4, say.

What do others think?

[1]: http://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/NestedGroups

**Comment by h-lame** [comment]
It should definitely be higher, yes.

**Comment by theseanything** [comment]
This repository has been deprecated - if this is still an issue re-raise in https://github.com/alphagov/rubocop-govuk
